db:
  image: postgres
  ports:
    - "5432:5432"

redis:
  image: redis

app:
  build: .
  command: bundle exec rails s -p 9292 -b 0.0.0.0
  volumes:
    - .:/usr/src/app
  ports:
    - "9292:9292"
  links:
    - db
    - redis
  environment:
    REDIS_URL: redis://redis:6379/0
