app:
  build: .
  environment:
    DATABASE_HOST: db
  links:
    - db
    - phantomjs
  ports:
    - "4000:4000"
  volumes:
    - .:/usr/src/app

db:
  image: postgres:latest
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
  volumes:
    - /var/lib/postgresql/data

redis:
  image: redis:latest

phantomjs:
  image: tyrbo/phantomjs:2.1.1
