db:
  image: postgres
  ports:
    - "5432:5432"

redis:
  image: redis

app:
  build: .
  command: bundle exec foreman start
  volumes:
    - .:/app
  ports:
    - "3333:3333"
  links:
    - db
    - redis
  environment:
    DATABASE_URL: postgres://postgres:postgres@db/
    RAILS_ENV: development
